{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.externalSecret.ssmPath }}/DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.ssmPath }}/DB_PASSWORD
{{- end }}
