apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/fawasam/k8s.git
    targetRevision: main
    path: helm/node-app
    helm:
      valueFiles:
        - values.yaml
        - values.dev.yaml          # dev overrides

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
