apiVersion: v2
name: node-app
description: Node.js app Helm chart for EKS
type: application
version: 1.0.0         # chart version (bump when you change the chart)
appVersion: "5.0.0"    # app version (your docker image version)
