apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: node-app-secret
  namespace: dev                        # scoped to dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: node-app-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: /node-app/dev/DB_USER      # dev SSM path

    - secretKey: DB_PASSWORD
      remoteRef:
        key: /node-app/dev/DB_PASSWORD  # dev SSM path
