apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: node-app-secret
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: node-app-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: /node-app/staging/DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /node-app/staging/DB_PASSWORD
